CREATE TABLE sessions(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id TEXT UNIQUE NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
session_token TEXT UNIQUE NOT NULL,
expired_time DATETIME NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) 
)
